---
title: PS270 Final Project
author: "Mallory Bottemiller"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

How does the presence of Zebra mussels affect the amount of recreation occurring in a fresh water lake? My hypothesis is that the presence of zebra mussels would cause a sharp decline in recreation levels. I believe this because people are less likely to use an environmental space they view as dangerous or degraded. Zebra mussel presence is perceived as dangerous and undesirable because of the damage they can cause to equipment, harm to people, and a decline in fish populations. My explanatory variable in this case is the presence of zebra mussels, which can be measured by population. My outcome variable of interest is the amount of recreation occurring in a given lake, this can be measured by counting annual visitors, fishing licenses, and/or boat launches. My hypothesis would be supported if a negative reltionship was shown between these variables, meaning when there are more zebra mussels there is less recreation. A positive reltionship would disprove this, which would be if a rise in zebra mussels was shown with a rise in recreation.